---
title: Maternity 
output: 
   flexdashboard::flex_dashboard:
     orientation: columns
     vertical_layout: fill
runtime: shiny
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, include = FALSE)
library(Hmisc)
library(GGally)
#library(tidytext)
library(SnowballC)
library(tidyverse)
#library(rjson)
library(RCurl)
```

```{r,include=FALSE}
############################################ Read Data #########################################
```
```{r, eval = FALSE}
#read_rds(file_path)
#write_csv(mph, file.path('data','mph.csv'))
#read.csv(text=httr:GET('https://github.com/harlananelson/data/blob/master/data/mph.rds'))
```

```{r global}
#install.packages('RCurl')
file_path <- 'https://github.com/harlananelson/data/blob/master/data/mph.rds?raw=true'
file_mph <- 'https://github.com/harlananelson/data/blob/master/data/mph.csv'
mph <- read.csv(text = file_path)  %>% 
  mutate(All = TRUE)

```


```{r, include=FALSE}
################################   Non reactive Functions ######################################
```

```{r}
#' Filter the data based on the selected measures
#' 
#' Filter the data based on the selected measures,  account the selecting All measures
#' 
#' @param d A data set to be piped into the selection code
#' @param measure_list  A list of the selected measures, can be `All`
#'
#' @return A data frame with the records containing the selected measures.
filter_data_by_measure <- function(d, measure_list){
  d  %>% 
    filter(measure %in% measure_list | 'All' %in% measure_list)  
}
```

```{r}
#' Filter the data based on the selected tags
#' 
#' Filter the data based on the selected tags,  account the selecting 'All' tags
#' 
#' @param d A data set to be piped into the selection code
#' @param tags_list  A list of the selected tags, can be `All`
#'
#' @param d Source data frame
#' @return A data frame with the records containing the selected tags .
filter_data_by_tag <- function(d, tag_list){
  d  %>% 
    filter(tag %in% tag_list | 'All' %in% tag_list)  
}
```

```{r}
#' Filter the data based on a topics filter list
#'
#' The data is subset based on choices, given these choices, filter the data.
#'
#' @param d Source data frame
#' @param filter_list A list of the topics choices.
#'
#' @return A data frame with the select records where the topics listed are TRUE
filter_data_by_topic <- function(d, topic_list){
  d  %>% 
    filter(!!! rlang::syms(topic_list))
}

```


```{r}
#'  filter data based on user selection for tag, measure and topic
#' 
#'  filter data based on user selection for tag, measure and topic
#'
#' @param d Source data frame
filter_data <- function(d, measure_list, tag_list, topic_list){
  d  %>% 
    filter_data_by_measure(measure_list) %>% 
    filter_data_by_tag(tag_list)   %>% 
    filter_data_by_topic(topic_list)
}
```

```{r, eval=FALSE}
# filter data based on user selection
filter_data <- function(d, measure_list, tag_list){
  d  %>% 
    filter(measure %in% measure_list | 'All' %in% measure_list) %>% 
    filter(tag     %in% tag_list     | 'All' %in% tag_list)
}
```

```{r, eval=FALSE}
# Function to Update the list for the measures.
choices_measure <- function(d, tag_list, topic_list){ 
  d %>% 
    filter_data_by_tag(tag_list) %>% 
    select(measure) %>% 
    distinct %>% 
    pull(measure) %>% 
    prepend("A")
}
```

```{r, eval=TRUE}
#' Function to Update the choices list for the measures.
#'
#' Function to Update the choices list for the measures.
#'
#' @param d The soure data frame before any filtering
#' @param tag_list  The list of chosen tag
#' @param topics_list The list of chosen topics
#' @result a list of measures where there are data points after measure and topic filtering
choices_measure <- function(d, tag_list, topic_list){ 
  d %>% 
    filter_data_by_tag(tag_list) %>% 
    filter_data_by_topic(topic_list) %>% 
    select(measure) %>% 
    filter(measure != 'All') %>% 
    distinct %>% 
    pull(measure)  
}

```


```{r, eval=TRUE}
#' update the choice list for the tags.
#'
#' Given a current measure and topics list, give all the tags where there is data.     
#' 
#' @param d The full data set
#' @param measure_list The list of selected measures.
#' @param topic_list The list of the selected topics.
choices_tag <- function(d, measure_list, topic_list ) { 
  d %>% 
    filter_data_by_measure(measure_list) %>% 
    filter_data_by_topic(topic_list) %>% 
    select(tag) %>% 
    filter(tag != 'All') %>% 
    distinct %>% 
    arrange(tag) %>% 
    pull(tag)   
    
} 
```


```{r}
#' update the list for the logical.
#'
#' Given a current choice list, give all the other topics that have at least one record with a TRUE value

choices_topic <- function(d, measure_list, tag_list, topic_list ) { 
  d %>% 
    filter_data_by_measure(measure_list) %>% 
    filter_data_by_tag(tag_list) %>% 
    filter_data_by_topic(topic_list) %>% 
    select_if(is.logical)    %>%  
    gather %>%  
    distinct %>%  
    filter(value) %>%  
    filter(key != 'All') %>%  
    pull(key)    
}
```

```{r, include=FALSE}
######################################   Reactive Functions  ##############################################
```



```{r}
# Filter data (call function to filter data) when user requests the filter action.
filtered_data <- eventReactive(input$filter_data,{
   mph %>% 
    filter_data(input$measure, input$tag, input$topic) 
} )
```

```{r}
# Spread data for correlation Plot
spread_data <- eventReactive(input$filter_data,{ 
  d <- filtered_data() %>%  
    mutate(key = str_c(tag, " ", measure)) %>%  
    #mutate(key = str_c(tag)) %>%  
    select(COUNTY, key, value ) %>%  
    spread(key = key, value = value)  
} )
```

```{r, include=FALSE}
###################################   Create extra set of reactiveValues  #############################
```

```{r}
app_input <- reactiveValues()

```

```{r}
app_input$measure <- eventReactive(input$measure,{
  input$measure
})
```

```{r}
app_input$tag <- eventReactive(input$tag,{
  input$tag
})
```

```{r}
app_input$topic <- eventReactive(input$topic,{
  input$topic
})
```

```{r}
################################################ Compound reactions ######################################################
```

```{r}
measure_topic <-reactive({
  paste(input$measure, input$topic)
})
```

```{r}
tag_topic <- reactive({
  paste(input$tag, input$topic)
})
```

```{r}
measure_tag <- reactive({
  paste(input$measure, input$tag)
})
```

```{r}
###################################  Keep track of current choices ##############################################
```

```{r}
# Update the list for the measures.
choices_measure_update <- eventReactive(input$tag,{
  choices_measure(mph, input$tag)
})
```

```{r}
#update the list for the tags.
choices_tag_update <- eventReactive(input$measure,{ 
  choices_tag(mph,input$measure)
})
```

```{r, include=FALSE}
##################################   Draw User Interface ######################################
```

```{r}
observeEvent(measure_topic(), {  
  choices_list_tag <- choices_tag(mph,input$measure, input$topic)
  updateCheckboxGroupInput(session,"tag", label = h3("Population"),
                           choices = c('All',choices_list_tag),
                           selected = app_input$tag())
})
```

```{r}
observeEvent(tag_topic(), {  
  choices_list_measure <- choices_measure(mph,input$tag, input$topic)
  updateCheckboxGroupInput(session,"measure", label = h3("Measurement Type"),
                           choices = c('All',choices_list_measure),
                           selected = app_input$measure())
})
```

```{r, eval=FALSE} 
observeEvent(measure_tag(),{ 
  choices_list_topic <- choices_topic(mph,input$measure,input$tag,input$topic) 
  updateCheckboxGroupInput(session, "topic", label = h3("Topic Selection"),   
                     choices = c('All',choices_list_topic),  
                     selected = input$topic]) 
})
  
```

```{r, include=FALSE}
##################################################Output ######################################################
```

```{r}
# Create a density plot
output$density_measure <-  renderPlot({
 filtered_data() %>% 
  ggplot(aes(x = value, group = measure, color = measure)) +
  geom_density() +
  ggplot2::scale_x_log10()  
   }) 
  
```


```{r}
output$density_tag <-  renderPlot({
 filtered_data() %>% 
  ggplot(aes(x = value, group = tag, color = tag)) +
  geom_density() +
  ggplot2::scale_x_log10()  
   }) 
  
```

```{r}
output$corr_plot <- renderPlot({ 
  d <- spread_data() 
  dm <- as.matrix(d %>% select(-COUNTY))
  #dimnames(dm) <- NULL
  dm %>% ggcorr() 
})
```

```{r}
###################################  UI ############################################
```

Column{.sidebar data-width=300}
-----------------------------------------------------------------------

```{r, include=TRUE}
actionLink("filter_data", "Filter Data")
```

```{r, include=TRUE}
actionLink("density", "Create density plot")
```

```{r, include=TRUE}
choices_list_tag <- choices_tag(mph,c('All'),c('All'))
checkboxGroupInput("tag", label = h3("Population"),  
                   choices = c('All',choices_list_tag), 
                   selected = 'All')
```

```{r, include=TRUE} 
choices_list_measure <- choices_measure(mph,c('All'),c('All'))
checkboxGroupInput("measure", label = h3("Measurement Type"),  
                   choices = c('All',choices_list_measure), 
                   selected = 'All')
```

```{r, include=TRUE} 

choices_list_topic <- choices_topic(mph,c('All'),c('All'),c('All'))
checkboxGroupInput("topic", label = h3("Topic Selection"),  
                   choices = c('All',choices_list_topic), 
                   selected = 'All')
```

Output {.tabset}
-----------------------------------------------------------------------

### Data Filter

```{r, include=TRUE}
renderTable({
    filtered_data() %>% 
    arrange(COUNTY)
})
```


### Density Plot by Tag

```{r, include=TRUE}
    plotOutput("density_tag")
```

### Density Plot by Measure

```{r, include=TRUE}
    plotOutput("density_measure")
```


### Plot Data

```{r, include=TRUE}
renderTable({
  filtered_data() %>% 
    select(COUNTY, measure ,tag, value)
    
})
```

### Corr Plot Data

```{r, include=TRUE}
renderTable({
  spread_data()
})
```

### Correlation Plot

```{r, include=TRUE}
plotOutput("corr_plot")
```

### input measure

```{r, include=TRUE}
renderText({
   m <- input$measure
   str(m)
})
```
### choices measure

```{r include=TRUE}
renderText(({ 
  choices_list_measure <- choices_measure(mph,input$tag, input$topic)
  unlist(choices_list_measure) 
}))

```
